# --------------------------------------------------------------------------
# Referentiels
# --------------------------------------------------------------------------
api_JID_repos_list:
    path:  /repos{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Components\Repos:list, repoId: ojs_db, outputFormat: ~  }
    methods: [GET]

# ==========================================================================
# COMPONENTS
# --------------------------------------------------------------------------
# Clusters
# --------------------------------------------------------------------------
api_JID_clusters_list:
    path:  /repos/{repoId}/clusters{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Components\Clusters:list, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

api_JID_clusters_get:
    path:  /repos/{repoId}/clusters/{schedulerId}/members{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Components\Clusters:get, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

# --------------------------------------------------------------------------
# Instances
# --------------------------------------------------------------------------
api_JID_instances_list:
    path:  /repos/{repoId}/instances{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Components\Instances:list, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

# --------------------------------------------------------------------------
# Spoolers
# --------------------------------------------------------------------------
api_JID_spoolers_list:
    path:  /repos/{repoId}/spoolers{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Components\Spoolers:list, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

api_JID_repos_create:
    path:  /repos/{repoId}/spoolers{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Components\Spoolers:create, repoId: ojs_db, outputFormat: ~ }
    methods: [POST]

# --------------------------------------------------------------------------
# History
# --------------------------------------------------------------------------
api_JID_history-orders_list:
    path:  /repos/{repoId}/history-orders{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\History\Orders:list, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

api_JID_history-order-steps_list:
    path:  /repos/{repoId}/history-order-steps{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\History\OrderSteps:list, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

api_JID_history-jobs_list:
    path:  /repos/{repoId}/history-jobs{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\History\Jobs:list, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

# ==========================================================================
# SCHEDULER
# ==========================================================================

# --------------------------------------------------------------------------
# Orders
# --------------------------------------------------------------------------
api_JID_orders_list:
    path:  /repos/{repoId}/orders{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Scheduler\Orders:list, repoId: ojs_db, outputFormat: ~  }
    methods: [GET]

api_JID_orders_detail:
    path:  /repos/{repoId}/orders/detail{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Scheduler\Orders:get, repoId: ojs_db, outputFormat: ~  }
    methods: [GET]

api_JID_orders_payload:
    path:  /repos/{repoId}/orders/payload{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Scheduler\Orders:payload, repoId: ojs_db, outputFormat: ~  }
    methods: [GET]

# --------------------------------------------------------------------------
# Chains
# --------------------------------------------------------------------------
api_JID_chains_list:
    path:  /repos/{repoId}/chains{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Scheduler\Chains:list, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

# --------------------------------------------------------------------------
# Nodes
# --------------------------------------------------------------------------
api_JID_nodes_list:
    path:  /repos/{repoId}/nodes{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Scheduler\Nodes:list, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

# --------------------------------------------------------------------------
# Jobs
# --------------------------------------------------------------------------
api_JID_jobs_list:
    path:  /repos/{repoId}/jobs{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Scheduler\Jobs:list, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

# --------------------------------------------------------------------------
# Tasks
# --------------------------------------------------------------------------
api_JID_tasks_list:
    path:  /repos/{repoId}/tasks{outputFormat}
    defaults: { _controller: AriiJIDBundle:API\Scheduler\Tasks:list, repoId: ojs_db, outputFormat: ~ }
    methods: [GET]

# ==========================================================================
# PLAN
# ==========================================================================

# --------------------------------------------------------------------------
# Orders
# --------------------------------------------------------------------------
api_JID_plan_orders_list:
    path:  /repos/{repoId}/plan/orders
    defaults: { _controller: AriiJIDBundle:API\Plan\Orders:list, repoId: ojs_db }
    methods: [GET]

# ==========================================================================
# STATUS
# ==========================================================================
# --------------------------------------------------------------------------
# Errors
# --------------------------------------------------------------------------
api_JID_status_errors_list:
    path:  /repos/{repoId}/status/errors
    defaults: { _controller: AriiJIDBundle:API\Status\Errors:list, repoId: ojs_db }
    methods: [GET]

# --------------------------------------------------------------------------
# Orders
# --------------------------------------------------------------------------
api_JID_status_orders_list:
    path:  /repos/{repoId}/status/orders
    defaults: { _controller: AriiJIDBundle:API\Status\Orders:list, repoId: ojs_db }
    methods: [GET]

# --------------------------------------------------------------------------
# Chains
# --------------------------------------------------------------------------
api_JID_status_chains_list:
    path:  /repos/{repoId}/status/chains
    defaults: { _controller: AriiJIDBundle:API\Status\Chains:list, repoId: ojs_db }
    methods: [GET]

# --------------------------------------------------------------------------
# Jobs
# --------------------------------------------------------------------------
api_JID_status_jobs_list:
    path:  /repos/{repoId}/status/jobs
    defaults: { _controller: AriiJIDBundle:API\Status\Jobs:list, repoId: ojs_db }
    methods: [GET]

# --------------------------------------------------------------------------
# Nodes
# --------------------------------------------------------------------------
api_JID_status_nodes_list:
    path:  /repos/{repoId}/status/nodes
    defaults: { _controller: AriiJIDBundle:API\Status\Nodes:list, repoId: ojs_db }
    methods: [GET]

# ==========================================================================
# HISTORY
# ==========================================================================

# --------------------------------------------------------------------------
# Orders
# --------------------------------------------------------------------------
api_JID_orders_history_list:
    path:  /repos/{repoId}/orders_history
    defaults: { _controller: AriiJIDBundle:API\History\OrdersHistory:list, repoId: ojs_db }
    methods: [GET]

api_JID_orders_history_get:
    path:  /repos/{repoId}/orders_history/{orderId}
    defaults: { _controller: AriiJIDBundle:API\History\OrdersHistory:get, repoId: ojs_db }
    methods: [GET]

api_JID_orders_history_steps:
    path:  /repos/{repoId}/orders_history/{orderId}/steps
    defaults: { _controller: AriiJIDBundle:API\History\OrdersHistory:steps, repoId: ojs_db }
    methods: [GET]

# --------------------------------------------------------------------------
# Jobs
# --------------------------------------------------------------------------
api_JID_jobs_list:
    path:  /repos/{repoId}/jobs
    defaults: { _controller: AriiJIDBundle:API\History\Jobs:list, repoId: ojs_db }
    methods: [GET]

api_JID_runs_create:
    path:  /repos/{repoId}/jobs
    defaults: { _controller: AriiJIDBundle:API\History\Jobs:create, repoId: ojs_db }
    methods: [POST]

# ==========================================================================
# COMPONENTS
# ==========================================================================

api_JID_inventory_instances_list:
    path:  /repos/{repoId}/inventory/instances
    defaults: { _controller: AriiJIDBundle:API\Inventory\Instances:list, repoId: ojs_db }
    methods: [GET]

# ==========================================================================
# MAINTENANCE
# ==========================================================================

# --------------------------------------------------------------------------
# Orders
# --------------------------------------------------------------------------
api_JID_archive_orders:
    path:  /repos/{repoId}/archive/orders
    defaults: { _controller: AriiJIDBundle:API\Maintenance\Archive:orders, repoId: ojs_db }
    methods: [GET]

api_JID_clean_steps:
    path:  /repos/{repoId}/purge/steps
    defaults: { _controller: AriiJIDBundle:API\Maintenance\Purge:steps, repoId: ojs_db }
    methods: [GET]
    
api_JID_clean_orders:
    path:  /repos/{repoId}/purge/orders
    defaults: { _controller: AriiJIDBundle:API\Maintenance\Purge:orders, repoId: ojs_db }
    methods: [GET]
