parameters:
#    arii_jid.example.class: Arii\JIDBundle\Example

services:
#    arii_jid.example:
#        class: %arii_jid.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    jid.twig.jid_extension:
        class: Arii\JIDBundle\Twig\JIDExtension
        tags:
            - { name: twig.extension }

# Couche DB Historique
    arii_jid.Plan:
        class: Arii\JIDBundle\Service\AriiPlan
        arguments: [ "@arii_core.portal", "@arii_core.tools"]

    arii_jid.History:
        class: Arii\JIDBundle\Service\AriiHistory
        arguments: [ "@arii_core.portal", "@arii_core.tools"]

    arii_jid.Inventory:
        class: Arii\JIDBundle\Service\AriiInventory
        arguments: [ "@arii_core.portal", "@arii_core.tools"]

    arii_jid.Report:
        class: Arii\JIDBundle\Service\AriiReport
        arguments: [ "@arii_core.portal", "@arii_core.tools"]

# Definition du module
    arii_jid.sos:
        class: Arii\JIDBundle\Service\AriiSOS
        arguments: [ "@arii_core.portal", "@arii_core.dhtmlx", "@arii_core.sql" ]

# Passage en doctrine
    arii_jid.history2:
        class: Arii\JIDBundle\Service\AriiHistory2
        arguments: [ "@arii_core.portal", "@arii_core.tools"]

    arii_jid.graphviz:
        class: Arii\JIDBundle\Service\AriiGraphviz
        arguments: [  "@arii_core.tools", "@arii_core.dhtmlx", "@arii_core.sql"  ]

# V2 en ORM
    arii.jid:
        class: Arii\JIDBundle\Service\AriiJID
        arguments: [ "@arii_core.portal", @doctrine, "@arii_core.date", "@arii_core.tools" ]
        
