# --------------------------------------------------------------------------
# Spooler
# --------------------------------------------------------------------------
api_JOC_spoolers_list:
    path:  /spoolers{outputFormat}
    defaults: { _controller: AriiJOCBundle:API\Spoolers:list, outputFormat: ~ }
    methods: [GET]

api_JOC_spoolers_get:
    path:  /spoolers/{spoolerId}
    defaults: { _controller: AriiJOCBundle:API\Spoolers:get }
    methods: [GET]

# --------------------------------------------------------------------------
# Orders
# --------------------------------------------------------------------------
api_JOC_orders_list:
    path:  /orders
    defaults: { _controller: AriiJOCBundle:API\Orders:list }
    methods: [GET]

api_JOC_orders_get:
    path:  /orders/{orderId}
    defaults: { _controller: AriiJOCBundle:API\Orders:get }
    methods: [GET]

api_JOC_orders_steps:
    path:  /orders/{orderId}/steps
    defaults: { _controller: AriiJOCBundle:API\Orders:steps }
    methods: [GET]

# --------------------------------------------------------------------------
# Jobs
# --------------------------------------------------------------------------
api_JOC_jobs_list:
    path:  /jobs
    defaults: { _controller: AriiJOCBundle:API\Repos:list }
    methods: [GET]

api_JOC_jobs_create:
    path:  /jobs
    defaults: { _controller: AriiJOCBundle:API\Repos:create }
    methods: [POST]

# --------------------------------------------------------------------------
# Runs
# --------------------------------------------------------------------------
api_JOC_runs_list:
    path:  /runs
    defaults: { _controller: AriiJOCBundle:API\Runs:list }
    methods: [GET]

api_JOC_runs_create:
    path:  /runs
    defaults: { _controller: AriiJOCBundle:API\Runs:create }
    methods: [POST]
