<?php

namespace Arii\ACKBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostRepository extends EntityRepository
{
    public function listStates($ok,$warning,$critical) {        
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.id,e.name,e.title,e.description,e.state,e.state_time')
        ->orderBy('e.state_time','DESC');
        if ($ok)
            $q->orWhere("e.state = 'OK'");
        if ($warning)
            $q->orWhere("e.state = 'WARNING'");
        if ($critical)
            $q->orWhere("e.state = 'CRITICAL'");
        return $q->getQuery()->getResult();
    }
    
    public function getNb($state='OPEN') {
        return $this->createQueryBuilder('e')
            ->select('COUNT(e)')
            ->where('e.state = :state')
            ->setParameter('state', $state)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function listState($state) {        
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.id,e.event_type,e.name,e.title,e.description,e.state,e.state_time')
        ->where('e.state = :state')
        ->orderBy('e.state_time','DESC')
        ->setParameter('state',$state)
        ->getQuery();
        return $q->getResult();
    }

    public function pieNotOK() {        
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.status as STATUS,count(e) as NB')
        ->where('e.status != :status')
        ->orderBy('e.status')
        ->groupBy('e.status')
        ->setParameter('status', 'OK')
        ->getQuery();
        return $q->getResult();
    }

    public function Host($id) {
        
        $q = $this
        ->createQueryBuilder('e')
        ->select("e.id","e.name","e.title","e.description","e.host","e.ip_address","e.port","e.state_time","e.state_information",
                "e.acknowledged","e.downtimes","e.downtimes_info","e.downtimes_user",
                "e.last_state_change","e.last_time_up","e.last_time_down","e.last_time_unreachable","e.latency")
        ->where('e.id = :id')
        ->setParameter('id', $id)
        ->getQuery();

        return $q->getResult();
    }    
}
