<?php

namespace Arii\ACKBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
    
    public function listNodes($id) {        
        $q = $this
        ->createQueryBuilder('e')
        ->select('e')
        ->Where("e.obj_from = :id")
        ->orWhere("e.obj_to = :id")
        ->setParameter('id', $id);
        return $q->getQuery()->getResult();
    }
        
}
