<?php

namespace Arii\ACKBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProbeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProbeRepository extends EntityRepository
{
    public function findHosts($Probe = 'HOST') {        
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.id,e.name,e.title,e.description')
        ->orderBy('e.name,e.obj_type','DESC')
        ->where('e.obj_type = :Probe')
        ->orderBy('e.name')
        ->setParameter('Probe', $Probe )
        ->getQuery();
        return $q->getResult();
    }
}
