parameters:

    database_ojs_driver: 
    database_ojs_host: 
    database_ojs_port: 
    database_ojs_name: 
    database_ojs_user: 
    database_ojs_password: 
    database_ojs_service:  
    database_ojs_servicename: 

    database_ats_driver: 
    database_ats_host: 
    database_ats_port: 
    database_ats_name: 
    database_ats_user: 
    database_ats_password: 
    database_ats_service:  
    database_ats_servicename: 

    database_ats2_driver: 
    database_ats2_host: 
    database_ats2_port: 
    database_ats2_name: 
    database_ats2_user: 
    database_ats2_password: 
    
    database_ojs2_driver: 
    database_ojs2_host: 
    database_ojs2_port: 
    database_ojs2_name: 
    database_ojs2_user: 
    database_ojs2_password: 