parameters:

    database_ojs_driver: oci8
    database_ojs_host: HOST1
    database_ojs_port: 1521
    database_ojs_name: INSTANCE1
    database_ojs_user: user
    database_ojs_password: password
    database_ojs_service:  true
    database_ojs_servicename: SERVICE

    database_ats_driver: oci8
    database_ats_host: HOST2
    database_ats_port: 1521
    database_ats_name: INSTANCE2
    database_ats_user: user    
    database_ats_password: password
    database_ats_service:  true
    database_ats_servicename: SERVICE

    database_ats2_driver: oci8
    database_ats2_host: HOST3
    database_ats2_port: 1521
    database_ats2_name: INSTANCE3
    database_ats2_user: user    
    database_ats2_password: password
    
    database_ojs2_driver: oci8
    database_ojs2_host: HOST4
    database_ojs2_port: 1521
    database_ojs2_name: INSTANCE4
    database_ojs2_user: user
    database_ojs2_password: password