arii_homepage:
    path:  /
    defaults: {_controller: AriiCoreBundle:Default:default }
    
arii_Alert_index:
    path:  /alerts
    defaults: {_controller: AriiCoreBundle:Default:default }
    
arii_home:
    path:  /{_locale}/home
    defaults: { _controller: AriiCoreBundle:Default:index, _lang: en  }
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# Arii common
# Utilisé par tous les modules
# ----------------------------------------
arii_common:
    resource: "@AriiCoreBundle/Resources/config/routing_arii.yml"
    prefix:   /{_locale}/arii
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

# ========================================
# API Bundle
# ----------------------------------------
arii_api:
    resource: "@AriiAPIBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/api
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

arii_api_REST:
    resource: "@AriiAPIBundle/Resources/config/routing_api.yml"
    prefix:   /api/v1
            
# ========================================
# Core Bundle
# ----------------------------------------
arii_core:
    resource: "@AriiCoreBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/home
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp

arii_core_REST:
    resource: "@AriiCoreBundle/Resources/config/routing_api.yml"
    prefix:   /api/v1

# ========================================
# Admin 
# ----------------------------------------
arii_Admin:
    resource: "@AriiAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# JOB
# ----------------------------------------
arii_JOB:
    resource: "@AriiJOBBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/job
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# ACK
# ----------------------------------------
arii_ACK:
    resource: "@AriiACKBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/ack
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

arii_ACK_import:
    resource: "@AriiACKBundle/Resources/config/routing_import.yml"
    prefix:   /import/ack

# ========================================
# Self
# ----------------------------------------
arii_Self:
    resource: "@AriiSelfBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/self
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# Plumb
# ----------------------------------------
arii_Plumb:
    resource: "@AriiPlumbBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/plumb
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# JID 
# ----------------------------------------
arii_jid:
    resource: "@AriiJIDBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/jid
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

arii_jid_inventory:
    resource: "@AriiJIDBundle/Resources/config/routing_Inventory.yml"
    prefix:   /{_locale}/jid/inventory
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

arii_jid_report:
    resource: "@AriiJIDBundle/Resources/config/routing_Report.yml"
    prefix:   /{_locale}/jid/report
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

arii_jid_API:
    resource: "@AriiJIDBundle/Resources/config/routing_api.yml"
    prefix:   /api/v1/bundles/jid
        
# ========================================
# DS 
# ----------------------------------------
arii_ds:
    resource: "@AriiDSBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/ds
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# MFT 
# ----------------------------------------
arii_mft:
    resource: "@AriiMFTBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/mft
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# Graphviz
# ----------------------------------------
arii_Graphviz:
    resource: "@AriiGraphvizBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/gvz
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# JOC
# ----------------------------------------
arii_JOC:
    resource: "@AriiJOCBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/joc
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# Report
# ----------------------------------------
arii_Report:
    resource: "@AriiReportBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/report
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 


arii_Report_import:
    resource: "@AriiReportBundle/Resources/config/routing_import.yml"
    prefix:   /import/report

# ========================================
# Autosys
# ----------------------------------------
arii_ATS:
    resource: "@AriiATSBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/ats
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

arii_ATS_API:
    resource: "@AriiATSBundle/Resources/config/routing_api.yml"
    prefix:   /api/v1/bundles/ats

# ----------------------------------------
# Housekeeping
# ----------------------------------------
arii_JID_purge:
    path:  /housekeeping/purge
    defaults: { _controller: AriiJIDBundle:DB:purge }

arii_JID_purge_history:
    path:  /housekeeping/purge_history
    defaults: { _controller: AriiJIDBundle:DB:purge_history }

arii_JID_purge_order_history:
    path:  /housekeeping/purge_order
    defaults: { _controller: AriiJIDBundle:DB:purge_order }

arii_JID_purge_history_out:
    path:  /housekeeping/purge/history/{DB}
    defaults: { _controller: AriiJIDBundle:DB:purgeHistory }

arii_JID_purge_orders_history_out:
    path:  /housekeeping/purge/orders/{DB}
    defaults: { _controller: AriiJIDBundle:DB:purgeOrdersHistory }
    
arii_JID_status_history:
    path:  /housekeeping/status
    defaults: { _controller: AriiJIDBundle:DB:status }

# ========================================
arii_JID_purge_history_public:
    path:  /public/purge/history
    defaults: { _controller: AriiJIDBundle:DB:purge_history }

arii_JID_purge_order_public:
    path:  /public/purge/orders
    defaults: { _controller: AriiJIDBundle:DB:purge_order }

arii_JID_purge_order_step_public:
    path:  /public/purge/steps
    defaults: { _controller: AriiJIDBundle:DB:purge_order_steps }

# ========================================
# User Bundle
# ----------------------------------------
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

arii_user:
    resource: "@AriiUserBundle/Resources/config/routing.yml"
    prefix:   /user/{_locale}
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp


# ========================================
# Time
# ----------------------------------------
arii_Time:
    resource: "@AriiTimeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/time
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

arii_Time_API:
    resource: "@AriiTimeBundle/Resources/config/routing_api.yml"
    prefix:   /api/v1/bundles/time
        
# ========================================
# I5
# ----------------------------------------
arii_I5:
    resource: "@AriiI5Bundle/Resources/config/routing.yml"
    prefix:   /{_locale}/i5
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# Blockly
# ----------------------------------------
arii_Blockly:
    resource: "@AriiBlocklyBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/blockly
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 

# ========================================
# Print serveurs
# ----------------------------------------
arii_Print:
    resource: "@AriiPRTBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/prt
    requirements:
        _locale: en|fr|es|de|cn|ar|ru|jp 
