security:
#    always_authenticate_before_granting: true    
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_SYSADMIN,ROLE_OPERATOR,ROLE_DEVELOPPER]
        ROLE_MANAGER:     [ROLE_USER,ROLE_OPERATOR,ROLE_DEVELOPPER]
        ROLE_OPERATOR:    [ROLE_USER]
        ROLE_DEVELOPPER:  [ROLE_USER]       
        ROLE_SYSADMIN:    [ROLE_ALLOWED_TO_SWITCH,ROLE_DEVELOPPER]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, app_users, in_memory]

        fos_userbundle:
            id: fos_user.user_provider.username

        app_users:
            ldap:
                service: app.ldap
                base_dn: dc=vaudoise,dc=ch
                search_dn: CN=s-at-devops-ldap,OU=Services,OU=PRD,OU=HQ,DC=vaudoise,DC=ch
                search_password: IWKc5ck8o6fY8fNnCT7F
                filter: (sAMAccountName={username})
                default_roles: ROLE_USER
                
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    client: { password: macpass, roles: [ 'ROLE_EXEC' ] }
                
    firewalls:
        ldap:
            provider:  app_users
            stateless: true
            pattern:   /doc/
            http_basic_ldap:
                service: app.ldap
                dn_string: "{username}@vaudoise.ch"

#        wsse_secured:
#            pattern:   /api/.*
#            stateless: true
#            wsse:      { lifetime: 30 }
#        rest:
#            pattern:    /api/.*
#            anonymous: false
#            http_basic:
#                realm: "Secured Area"
#                provider: fos_userbundle
                
        api:
            pattern:  ^/api/
            security: false

        mft:
            pattern:  ^/mft/
            security: false

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|pdf)/
            security: false

        self:
            pattern:  /self/
            security: false
            
        cron:
            pattern:  /cron/
            security: false

        doc:
            pattern:  /doc/
            security: false

        post:
            pattern:  /post/
            security: false
            
        public:
            pattern:  /(public)
            security: false

        todo:
            pattern:  /todo/
            security: false

        return:
            pattern:  /return/
            security: false
            
        report:
            pattern:  /(report)/
            security: false
            
        check:
            pattern:  /(check)/
            anonymous: false
            http_basic:
                realm: "Secured Area"
                provider: fos_userbundle
            
        user:
            pattern:  ^/(user)/
            security: false

        # Firewall pour le cache
        cache:
            pattern:    ^/cache
            anonymous: false
            http_basic:
                realm: "Secured Area"
                provider: fos_userbundle

        requests:
            pattern:  /(requests)/
            security: false

        login:
            pattern:   ^/(login$|register|resetting|sync_state)  # Les adresses de ces pages sont login, register 
            security: false
        
        main:
            pattern:    ^/  # Tout est protégé
            provider: app_users
            pattern:  ^/admin
            form_login_ldap:
                service: app.ldap
                dn_string: CN={username},OU=Standard,OU=Users,OU=PRD,OU=HQ,DC=vaudoise,DC=ch
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
            form_login:
                provider:    fos_userbundle  # On lit l'authentification au provider définit plus haut
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: arii_Home_index
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
                # invalidate_session: true
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
            remember_me:
                key:      %secret%        # On définit la clé pour le remember_me (%secret% est un parametre de parameters.ini)
                lifetime: 31536000 # 365 days in seconds
#                path:     /login
#                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
