<?php

namespace Arii\ACKBundle;

use Doctrine\ORM\EntityRepository;

/**
 * EntityHostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityHostRepository extends EntityRepository
{
}
