# ========================================
# Instances
# ----------------------------------------
api_ATS_instances:
    path:  /instances{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Instances:list, outputFormat: ~ }

# ========================================
# AlarmStates
# ----------------------------------------
api_ATS_alarmstates_list:
    path:  /instances/{instanceId}/alarmStates{outputFormat}
    defaults: { _controller: AriiATSBundle:API\alarmStates:list, instanceId: ACE, outputFormat: ~ }

api_ATS_alarmstates_state:
    path:  /instances/{instanceId}/alarmStates/{alarmState}{outputFormat}
    defaults: { _controller: AriiATSBundle:API\alarmStates:state, instanceId: ACE, outputFormat: ~ }

# ========================================
# Alarms
# ----------------------------------------
api_ATS_alarms_list:
    path:  /instances/{instanceId}/alarms{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Alarms:list, instanceId: ACE, outputFormat: ~ }

# ========================================
# Audit
# ----------------------------------------
api_ATS_audit_list:
    path:  /instances/{instanceId}/audit
    defaults: { _controller: AriiATSBundle:API\audit:list, instanceId: ACE, outputFormat: ~ }

api_ATS_audit_get:
    path:  /instances/{instanceId}/audit/{auditId}
    defaults: { _controller: AriiATSBundle:API\audit:get, instanceId: ACE, auditId: 1, outputFormat: ~ }

api_ATS_audit_jobs:
    path:  /instances/{instanceId}/audit/jobs
    defaults: { _controller: AriiATSBundle:API\audit:jobs, instanceId: ACE, outputFormat: ~ }


# ========================================
# Boxes
# ----------------------------------------
api_ATS_boxes_list:
    path:  /instances/{instanceId}/boxes
    defaults: { _controller: AriiATSBundle:API\Boxes:list, instanceId: ACE, outputFormat: ~ }

# ========================================
# Box
# ----------------------------------------
api_ATS_box_list:
    path:  /instances/{instanceId}/boxes/{jobName}/jobs{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Box:jobs, instanceId: ACE, jobName: ~, outputFormat: ~ }

# ========================================
# Jobs
# ----------------------------------------
api_ATS_jobs_list:
    path:  /instances/{instanceId}/jobs{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Jobs:list, instanceId: ACE, outputFormat: ~ }

# ========================================
# Job
# ----------------------------------------
api_ATS_job_audit:
    path:  /instances/{instanceId}/jobs/{jobName}/audit{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Job:audit, instanceId: ACE, jobName: ~, outputFormat: ~ }

api_ATS_job_code:
    path:  /instances/{instanceId}/jobs/{jobName}/code{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Job:code, instanceId: ACE, jobName: ~, outputFormat: ~ }

api_ATS_job_detail:
    path:  /instances/{instanceId}/jobs/{jobName}/detail{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Job:detail, instanceId: ACE, jobName: ~, outputFormat: ~ }

api_ATS_job_status:
    path:  /instances/{instanceId}/jobs/{jobName}/status{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Job:status, instanceId: ACE, jobName: ~, outputFormat: ~ }

api_ATS_job_logs:
    path:  /instances/{instanceId}/jobs/{jobName}/logs/{logType}{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Job:logs, instanceId: ACE, jobName: ~, logType: Out, outputFormat: ~ }

api_ATS_job_report:
    path:  /instances/{instanceId}/jobs/{jobName}/report{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Job:report, instanceId: ACE, jobName: ~, outputFormat: ~ }

api_ATS_job_runs:
    path:  /instances/{instanceId}/jobs/{jobName}/runs{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Job:runs, instanceId: ACE, jobName: ~, outputFormat: ~ }

api_ATS_job_runtimes:
    path:  /instances/{instanceId}/jobs/{jobName}/runtimes{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Job:runtimes, instanceId: ACE, jobName: ~, outputFormat: ~ }

api_ATS_job_events:
    path:  /instances/{instanceId}/jobs/{jobName}/events{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Job:events, instanceId: ACE, jobName: ~, outputFormat: ~ }

# ========================================
# Calendars
# ----------------------------------------
api_ATS_calendars_list:
    path:  /instances/{instanceId}/calendars{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Calendars:list, instanceId: ACE, outputFormat: ~ }

# ========================================
# Calendar
# ----------------------------------------
api_ATS_calendar_days:
    path:  /instances/{instanceId}/calendars/{calendarName}/days{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Calendar:days, instanceId: ACE, outputFormat: ~ }

api_ATS_calendar_jobs:
    path:  /instances/{instanceId}/calendars/{calendarName}/jobs{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Calendar:jobs, instanceId: ACE, outputFormat: ~ }
    
# ========================================
# Extended calendars
# ----------------------------------------
api_ATS_extendedcalendars_list:
    path:  /instances/{instanceId}/extended_calendars{outputFormat}
    defaults: { _controller: AriiATSBundle:API\ExtendedCalendars:list, instanceId: ACE, outputFormat: ~ }

# --------------------------------------------------------------------------
# Users
# --------------------------------------------------------------------------
api_ATSDB_users_list:
    path:  /instances/{instanceId}/users{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Users:list, instanceId: ACE, outputFormat: ~ }

# --------------------------------------------------------------------------
# Machines
# --------------------------------------------------------------------------
api_ATSDB_machines_list:
    path:  /instances/{instanceId}/machines{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Machines:list, instanceId: ACE, outputFormat: ~ }

# --------------------------------------------------------------------------
# Status
# --------------------------------------------------------------------------
api_ATSDB_status_list:
    path:  /instances/{instanceId}/status{outputFormat}
    defaults: { _controller: AriiATSBundle:API\Status:list, instanceId: ACE, outputFormat: ~ }
