services:
#    arii_ats.example:
#        class: Arii\ATSBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    arii_ats.autosys:
        class: Arii\ATSBundle\Service\AriiAutosys 
        arguments: [ "@arii_core.portal" ]
        
    arii_ats.state:
        class: Arii\ATSBundle\Service\AriiState
        arguments: [ "@arii_core.dhtmlx", "@arii_core.sql", "@arii_core.date", "@arii_core.tools"]

    arii_ats.state2:
        class: Arii\ATSBundle\Service\AriiState2
        arguments: [ "@arii_core.portal", "@arii_core.tools", "@arii_ats.autosys" ]

    arii_ats.Runs:
        class: Arii\ATSBundle\Service\AriiRuns
        arguments: [ "@arii_core.portal", "@arii_ats.autosys" ]

    arii_ats.Status:
        class: Arii\ATSBundle\Service\AriiStatus
        arguments: [ "@arii_core.portal", "@arii_ats.autosys" ]

    arii_ats.exec:
        class: Arii\ATSBundle\Service\AriiExec
        arguments: [ "@arii_core.exec" ]

    arii_ats.twig_string_loader:
        class:        "Twig_Loader_String"
        
    arii_ats.twig_string:
        class:        "%twig.class%"
        arguments:    [@arii_ats.twig_string_loader ]
