<?php

namespace Arii\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityStatusRepository extends EntityRepository
{
   public function findActivities()
   {
        return $this->createQueryBuilder('a')
            ->Select('(a.id) as id,a.spoolerId,a.jobChain,a.orderId,a.state,a.stateText,a.title,a.startTime,a.endTime')
            ->orderBy('a.startTime','desc')
            ->getQuery()
            ->getResult();
   }    
  
}