<?php

namespace Arii\MFTBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OperationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationsRepository extends EntityRepository
{
    public function findOperationsByTransfer($transferId) { 
        $q = $this->createQueryBuilder('e')
        ->select('e.id,e.name,e.title,e.env,e.description,e.step,e.ordering,'
                . 'e.source_path,e.target_path,e.source_files,e.target_files,e.client,e.expected_files,e.exit_if_nothing,'
                . '(e.source) as source_id,(e.target) as target_id,(e.parameters) as parameters_id')
        ->where('e.transfer = :transferId')
        ->orderBy('e.ordering')
        ->setParameter('transferId',$transferId)                
        ->getQuery();
        return $q->getResult();
    }

}
