<?php

namespace Arii\MFTBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartnersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnersRepository extends EntityRepository
{
    public function findPartners() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.id,e.name,e.title,e.description,c.id as category_id,c.name as category')
        ->leftjoin('AriiCoreBundle:Category','c',\Doctrine\ORM\Query\Expr\Join::WITH,'e.category = c.id')        
        ->orderBy('e.title')
        ->getQuery();
        return $q->getResult();
    }
    
}
