<?php

namespace Arii\MFTBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SummaryRepository extends EntityRepository
{
    public function findSummaries() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.id,e.name,e.title,e.description,e.source,e.target,e.operation,e.data,e.protocol')
        ->orderBy('e.title')
        ->getQuery();
        return $q->getResult();
    }
    
}
