<?php

namespace Arii\MFTBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransmissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransmissionsRepository extends EntityRepository
{

    public function findTransmissions($Filter=[]) { 
        $q = $this->createQueryBuilder('e')
        ->select('e.id,e.source_file,e.target_file,e.start_time,e.end_time,e.duration,e.status,e.pid,e.file_size,e.md5');
        # Filtrage
        if (isset($Filter['limit']))
            $q->setMaxResults($Filter['limit']);
        if (isset($Filter['sourceFile']))
            $q->andWhere("e.source_file like :sourceFile")
            ->setParameter('sourceFile',$Filter['sourceFile'] );
        if (isset($Filter['startTime']))
            $q->andWhere("e.start_time > :startTime")
            ->setParameter('startTime',$Filter['startTime'] );
        return $q->getQuery()->getResult();
    }
    
}
