# --------------------------------------------------------------------------
# Code
# --------------------------------------------------------------------------
api_Time_code_list:
    path:  /code
    defaults: { _controller: AriiTimeBundle:API\Code:list }
    methods: [GET]

# --------------------------------------------------------------------------
# Zones
# --------------------------------------------------------------------------
api_Time_zones_list:
    path:  /zones
    defaults: { _controller: AriiTimeBundle:API\Zones:list }
    methods: [GET]

api_Time_zones_create:
    path:  /zones
    defaults: { _controller: AriiTimeBundle:API\Zones:create }
    methods: [POST]
