services:
    arii_time.code:
        class: Arii\TimeBundle\Service\AriiTimeCode
        arguments: [ "@arii_core.date" ]

    arii_time.db:
        class: Arii\TimeBundle\Service\AriiTimeDB
        arguments: [ "@arii_core.portal" ]
