# --------------------------------------------------------------------------
# PAGES PRINCIPALES
# --------------------------------------------------------------------------
arii_API_index:
    path:  /
    defaults: { _controller: AriiJIDBundle:Default:index }

arii_API_swagger:
    path:  /swagger
    defaults: { _controller: AriiAPIBundle:Default:swagger }

arii_API_readme:
    path:  /readme
    defaults: { _controller: AriiAPIBundle:Default:readme }

xml_API_toolbar:
    path:  /toolbar.xml
    defaults: { _controller: AriiAPIBundle:Default:toolbar }

json_API_ribbon:
    path:  /ribbon.json
    defaults: { _controller: AriiAPIBundle:Default:ribbon }

xml_API_menu:
    path:  /menu.xml
    defaults: { _controller: AriiAPIBundle:Default:menu }
