<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoAuditInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoAuditInfoRepository extends EntityRepository
{
    public function findSendevent() {        
        $q = $this
        ->createQueryBuilder('i')
        ->select('m.auditInfoNum', 'm.seqNo','m.attribute','m.value1','m.value2','m.isEdit','i.entity','i.time','i.type')
        ->leftjoin('AriiATSBundle:UjoAuditMsg','m',\Doctrine\ORM\Query\Expr\Join::WITH,'i.auditInfoNum = m.auditInfoNum')
        ->where('i.type = :type')
        ->andWhere('m.attribute = :attr')
        ->andWhere('m.seqNo = :seq')
        ->orderBy('i.time','desc')
        ->setParameter('type','S')
        ->setParameter('attr','command')
        ->setParameter('seq','3')
        ->setMaxResults(1000)
        ->getQuery();
        return $q->getResult();
    }

    public function findJobs() {        
        $q = $this
        ->createQueryBuilder('i')
        ->select('m.auditInfoNum', 'm.seqNo','m.attribute','m.value1','m.value2','m.isEdit','i.entity','i.time','i.type')
        ->leftjoin('AriiATSBundle:UjoAuditMsg','m',\Doctrine\ORM\Query\Expr\Join::WITH,'i.auditInfoNum = m.auditInfoNum')
        ->where('i.type = :type')
        ->andWhere('m.seqNo = :seq')
        ->orderBy('i.time','desc')
        ->setParameter('type','J')
        ->setParameter('seq','1')
        ->setMaxResults(1000)
        ->getQuery();
        return $q->getResult();
    }

}
