<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoAuditMsgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoAuditMsgRepository extends EntityRepository
{

    public function findJob($id) {        
        $q = $this
        ->createQueryBuilder('m')
        ->select('m.seqNo','m.attribute','m.value1','m.value2','m.isEdit')
        ->where('m.auditInfoNum = :id')
        ->orderBy('m.seqNo')
        ->setParameter('id', $id)
        ->setMaxResults(1000)
        ->getQuery();
        return $q->getResult();
    }    
        
}
