<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoCalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoCalendarRepository extends EntityRepository
{

    public function findCalendars($Filter) {    
        $q = $this
        ->createQueryBuilder('c')
        ->select('c.name as calendarName,COUNT(c) as daysCount,min(c.day) as minDate,max(c.day) as maxDate')
        ->groupBy('c.name')
        ->orderBy('c.name')
        ->setMaxResults(1000);    
        if (isset($Filter['calendarName'])) {
            $q->andWhere('c.name like :calendarName')
            ->setParameter('calendarName',$Filter['calendarName']); 
        }
        return $q->getQuery()
                ->getResult();
    }    

    public function findDays($calendarName,$Filter=[]) {   
       
        $q = $this
        ->createQueryBuilder('c')
        ->select('c.day')
        ->orderBy('c.day')
        ->setMaxResults(1000)
        ->Where('c.name = :calendarName')
        ->setParameter('calendarName', $calendarName); 
        if (isset($Filter['minDate'])) {
            $q->andWhere('c.day > :minDate')
            ->setParameter('minDate', $Filter['minDate']); 
        }
        if (isset($Filter['maxDate'])) {
            $q->andWhere('c.day < :maxDate')
            ->setParameter('maxDate', $Filter['maxDate']); 
        }   
        return $q->getQuery()
            ->getResult();
    }

}
