<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoHaProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoHaProcessRepository extends EntityRepository
{
    public function findSchedulers() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.pid,e.timeStamp,e.port,e.queueId,e.hostname,e.haDesignatorId,e.haStatusId')
        ->orderBy('e.haDesignatorId')
        ->getQuery();
        return $q->getResult();
    }    
}
