<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoJobstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoJobstRepository extends EntityRepository
{
    public function findProcesses() {
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.jobName,e.description,e.lastStart,e.lastEnd,e.status,e.statusTime,e.nextStart')
        ->where('e.jobType = 98')
        ->where('e.boxJoid = :box')
        ->orderBy('e.jobName')
        ->setParameter('box',0)
        ->getQuery();
        return $q->getResult();
    }

    public function findQueues() {
        $q = $this
        ->createQueryBuilder('e')
        ->select('e.jobName,e.jobLoad,e.status')
        ->getQuery();
        return $q->getResult();
    }
    
}
