<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoJobCondRepository extends EntityRepository
{
    public function findConditions($jobId,$Options) {
        $q = $this->createQueryBuilder('e')
        ->select('e.indx,e.operator,e.type,e.condJobName as jobName,e.testGlovalue,e.value,e.testGlovalue,e.condMode')
        ->where('e.joid = :jobId')
        ->andWhere("e.type != 'B'")
        ->setParameter('jobId',$jobId)
        ->distinct(); 
        
        if (isset($Options['dependencies'])) {
            $q->andWhere('e.condMode <= :condMode')
            ->setParameter('condMode',$Options['dependencies']);
        }
        
        return $q->orderBy('e.indx')
        ->getQuery()
        ->setMaxResults(100)
        ->getResult();
    }
    
}
