<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoJobRepository extends EntityRepository
{
    public function findIdByName($jobName) { 
        $q = $this->createQueryBuilder('e')
        ->select('e.joid')
        ->where('e.jobName = :jobName')
        ->andWhere('e.isCurrver = 1')
        ->setParameter('jobName',$jobName)
        ->orderBy('e.joid','desc')
        ->getQuery();        
        return $q->getResult();
    }
    
}
