<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoHaProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoMaProcessRepository extends EntityRepository
{
    public function findAppServers() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.commAlias,e.mgrAlias,e.pid,e.timeStamp,e.port,e.queueId,e.hostname,e.maDesignatorId,e.maStatusId')
        ->orderBy('e.commAlias')
        ->getQuery();
        return $q->getResult();
    }    
}
