<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoAlarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoMachineRepository extends EntityRepository
{

    public function findAgents() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.parentName,e.queName,e.type,e.agentName,e.machName,e.nodeName,e.machStatus,e.maxLoad,e.description,e.factor,e.heartbeatAttempts,e.heartbeatFreq,e.opsys,e.characterCode,e.port,e.prepjobid,e.provision')
        ->where('e.port > 0');
        return $q->orderBy('e.agentName')
                ->setMaxResults(1000)
                ->getQuery()
                ->getResult();
    }

    public function findQueues() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.parentName,e.queName,m.machName,m.machStatus,m.maxLoad,m.opsys')                
        ->leftjoin('AriiATSBundle:UjoMachine','m',\Doctrine\ORM\Query\Expr\Join::WITH,'e.machName = m.machName')
        ->where('e.port = 0')
        ->andWhere('m.port <> 0');
        return $q->orderBy('e.parentName')
                ->setMaxResults(1000)
                ->getQuery()
                ->getResult();
    }

    public function findQueue($queue) { 
        $q = $this->createQueryBuilder('e')
        ->select('e.parentName,e.queName,m.machName,m.machStatus,m.maxLoad,m.opsys')                
        ->leftjoin('AriiATSBundle:UjoMachine','m',\Doctrine\ORM\Query\Expr\Join::WITH,'e.machName = m.machName')
        ->where('e.port = 0')
        ->andWhere('m.port <> 0')
        ->andWhere('e.parentName = :parent')
        ->setParameter('parent', $queue);
        
        return $q->orderBy('e.parentName')
                ->setMaxResults(1000)
                ->getQuery()
                ->getResult();
    }
    
}
