<?php

namespace Arii\ATSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UjoHaProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UjoWaitQueRepository extends EntityRepository
{
    public function findWaitQueues() { 
        
        $q = $this->createQueryBuilder('e')
        ->select('e.queName,e.jobLoad,e.joid,e.maxLoad,e.priority,e.stamp')
        ->orderBy('e.queName')
        ->getQuery();
        return $q->getResult();
    }    
}
