arii_ACK_index:
    pattern:  /
    defaults: { _controller: AriiACKBundle:Default:index }

arii_ACK_readme:
    pattern:  /readme
    defaults: { _controller: AriiACKBundle:Default:readme }

json_ACK_ribbon:
    pattern:  /ribbon.json
    defaults: { _controller: AriiACKBundle:Default:ribbon }

xml_ACK_toolbar:
    pattern:  /toolbar.xml
    defaults: { _controller: AriiACKBundle:Default:toolbar }

xml_ACK_tree:
    pattern:  /tree.xml
    defaults: { _controller: AriiACKBundle:Default:tree }

arii_ACK_alarms_list:
    pattern:  /alarms/list.xml
    defaults: { _controller: AriiACKBundle:Alarms:list }

arii_ACK_alarms_add:
    pattern:  /alarms/add/{id}
    defaults: { _controller: AriiACKBundle:Alarms:add }

#============================================================
# Network
#--------------------------------------------------------------------
arii_ACK_network:
    path:  /network
    defaults: { _controller: AriiACKBundle:Network:index }

xml_ACK_network_grid:
    path:  /network/grid.xml
    defaults: { _controller: AriiACKBundle:Network:grid }

html_ACK_network_info:
    path:  /network/info.html
    defaults: { _controller: AriiACKBundle:Network:info }

#============================================================
# Synchro
#--------------------------------------------------------------------
    