arii_JOB_index:
    pattern:  /
    defaults: { _controller: AriiJOBBundle:Default:index }

html_JOB_welcome:
    pattern:  /welcome.html
    defaults: { _controller: AriiJOBBundle:Default:welcome }
    
arii_JOB_readme:
    pattern:  /readme
    defaults: { _controller: AriiJOBBundle:Default:readme }

json_JOB_ribbon:
    pattern:  /ribbon.json
    defaults: { _controller: AriiJOBBundle:Default:ribbon }

xml_JOB_toolbar:
    pattern:  /toolbar.xml
    defaults: { _controller: AriiJOBBundle:Default:toolbar }

xml_JOB_tree:
    pattern:  /tree.xml
    defaults: { _controller: AriiJOBBundle:Default:tree }

# --------------------------------------------------------------------------
# Edition de la tache
# --------------------------------------------------------------------------
arii_JOB_tasks:
    path:  /tasks
    defaults: { _controller: AriiJOBBundle:Tasks:index }

html_JOB_tasks_welcome:
    path:  /tasks/welcome.html
    defaults: { _controller: AriiJOBBundle:Tasks:welcome }

xml_JOB_tasks_grid:
    path:  /tasks/grid.xml
    defaults: { _controller: AriiJOBBundle:Tasks:grid }

xml_JOB_task_form:
    path:  /task/form.xml
    defaults: { _controller: AriiJOBBundle:Task:form }

xml_JOB_task_files_grid:
    path:  /task/files.xml
    defaults: { _controller: AriiJOBBundle:Task:files }

xml_JOB_task_toolbar:
    path:  /task/edit/toolbar.xml
    defaults: { _controller: AriiJOBBundle:Task:toolbar }

