<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InventoryInstancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyPlanRepository extends EntityRepository
{

   public function findOrders()
   {       
        $q = $this->createQueryBuilder('e')
        ->select('e.id,e.schedulerId,e.jobChain,e.orderId,e.plannedStart,e.expectedEnd,e.periodBegin,e.repeatInterval,e.startStart,e.isAssigned,e.isLate,e.state,e.created,e.modified');
        return $q->orderBy('e.id','desc')
                ->setMaxResults(1000)
                ->getQuery()
                ->getResult();       
   }
}
