<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerOrdersRepository extends EntityRepository
{   
    // Pour la synchronisation des historique
    public function findStates() { 
        $q = $this->createQueryBuilder('e')
        ->select('e')
        ->setMaxResults(1000)
        ->getQuery();
        return $q->getResult();
    }
    
}
