<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerJobChainNodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerJobChainNodesRepository extends EntityRepository
{

    public function findStoppedNodes() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.spoolerId,e.clusterMemberId,e.jobChain,e.orderState,e.action')
        ->where("e.action='stop'")
        ->orderBy('e.spoolerId,e.jobChain,e.orderState')
        ->getQuery();
        return $q->getResult();
    }
    
    public function findSkippedNodes() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.spoolerId,e.clusterMemberId,e.jobChain,e.orderState,e.action')
        ->where("e.action='skipped'")
        ->orderBy('e.spoolerId,e.jobChain,e.orderState')
        ->getQuery();
        return $q->getResult();
    }
    
    // Pour la synchronisation des historique
    public function findStopped() { 
        $q = $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.action is not null')
        ->getQuery();
        return $q->getResult();
    }
    
}
