<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerTasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerTasksRepository extends EntityRepository
{   
    public function findTasks($Filter=[]) { 
        $q = $this->createQueryBuilder('e')
        ->select('e.spoolerId as spoolerName,e.taskId,e.clusterMemberId,e.jobName,e.enqueueTime,e.startAtTime,e.parameters,e.taskXml')
        ->orderBy('e.spoolerId,e.taskId')
        ->setMaxResults(1000);
        # Filtrage
        if (isset($Filter['limit']))
            $q->setMaxResults($Filter['limit']);
        return $q->getQuery()->getResult();
    }
}
