<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerJobChainNodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerJobChainNodesRepository extends EntityRepository
{

    public function findNodes($Filter=[]) { 
        $q = $this->createQueryBuilder('e')
        ->select('e.spoolerId as spoolerName,e.clusterMemberId,e.jobChain,e.orderState,e.action')
        ->orderBy('e.spoolerId,e.jobChain,e.orderState')
        ->setMaxResults(1000);
        # Filtrage
        if (isset($Filter['limit']))
            $q->setMaxResults($Filter['limit']);
        if (isset($Filter['isStopped']) and ($Filter['isStopped']=='true'))
            $q->andWhere("e.action = 'stop'");
        if (isset($Filter['isSkipped']) and ($Filter['isSkipped']=='true'))
            $q->andWhere("e.action = 'next_state'");
        return $q->getQuery()->getResult();
    }
    
}
