<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerClustersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerClustersRepository extends EntityRepository
{

   public function findClusters()
   {
        $q = $this->createQueryBuilder('e') // 
        ->select('e.schedulerId,max(e.lastHeartBeat) as lastHeartBeat,count(e.active) as active,count(e.dead) as dead')
        ->groupBy('e.schedulerId');
        return $q->orderBy('e.schedulerId')
                ->setMaxResults(1000)
                ->getQuery()
                ->getResult();
       
   }

   public function findMembers($schedulerId)
   {
        $q = $this->createQueryBuilder('e') // 
        ->select('e.memberId,e.schedulerId,e.lastHeartBeat,e.nextHeartBeat,e.active,e.dead,e.command,e.httpUrl,e.deactivatingMemberId,e.xml')
        ->where('e.schedulerId = :schedulerId')
        ->setParameter('schedulerId',$schedulerId);
        return $q->orderBy('e.schedulerId')
                ->setMaxResults(1000)
                ->getQuery()
                ->getResult();
       
   }
}
