<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerInstancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerInstancesRepository extends EntityRepository
{

   public function findInstances()
   {
        $q = $this->createQueryBuilder('e')
        ->select('e.id,e.schedulerId,e.hostname,e.tcpPort,e.udpPort,e.supervisorHostname,e.supervisorTcpPort,e.startTime,e.stopTime,e.dbName,e.workingDirectory,e.liveDirectory,e.logDir,e.includePath,e.iniPath,e.isService,e.isRunning,e.isPaused,e.isCluster,e.isAgent,e.isSosCommandWebservice,e.param,e.releaseNumber');
        return $q->orderBy('e.schedulerId')
                ->setMaxResults(1000)
                ->getQuery()
                ->getResult();
       
   }
}
