<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerJobChainsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerJobsRepository extends EntityRepository
{
    public function findStoppedJobs() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.spoolerId,e.clusterMemberId,e.path')
        ->where('e.stopped=1')
        ->getQuery();
        return $q->getResult();
    }
    
    // Pour la synchronisation des historique
    public function findJobs() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.spoolerId,e.clusterMemberId,e.path,e.stopped,e.nextStartTime')
        ->getQuery();
        return $q->getResult();
    }
}
