<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerJobChainsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerJobChainsRepository extends EntityRepository
{
    // Pour la synchronisation des historique
    public function findChains() { 
        $q = $this->createQueryBuilder('e')
        ->select('e.spoolerId,e.clusterMemberId,e.path,e.stopped')
        ->getQuery();
        return $q->getResult();
    }
       
    // Pour la synchronisation des historique
    public function findStopped() { 
        $q = $this->createQueryBuilder('e')
        ->select('e')
        ->where('e.stopped=1')
        ->getQuery();
        return $q->getResult();
    }
    
}
