<?php

namespace Arii\JIDBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SchedulerOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchedulerOrdersRepository extends EntityRepository
{   
    public function findOrders($Filter=[]) { 
        $q = $this->createQueryBuilder('e')
        ->select('e.spoolerId as spoolerName,e.id as OrderName,e.jobChain,e.title,e.priority,e.state,e.stateText,e.createdTime,e.modTime,e.ordering,e.payload,e.runTime,e.initialState,e.orderXml,e.distributedNextTime,e.occupyingClusterMemberId')
        ->orderBy('e.modTime','desc')
        ->setMaxResults(1000);
        # Filtrage
        if (isset($Filter['limit']))
            $q->setMaxResults($Filter['limit']);
        if (isset($Filter['isSuspended']) and $Filter['isSuspended']=='true')
            $q->andWhere("e.orderXml like '%suspended=\"yes\"%'");
        if (isset($Filter['state']))
            $q->andWhere('e.state like :state')
                ->setParameter('state',$Filter['state']);           
        return $q->getQuery()->getResult();
    }

    public function findSuspendedOrders() {
        $q = $this->createQueryBuilder('e')
        ->select('e.spoolerId,e.jobChain,e.id as orderId,e.title,e.priority,e.state,e.stateText,e.createdTime,e.modTime,e.ordering,e.payload,e.runTime,e.initialState,e.orderXml,e.distributedNextTime,e.occupyingClusterMemberId,e.orderXml')
        ->where("e.orderXml like '%suspended=\"yes\"%'")
        ->orderBy('e.modTime','desc')                
        ->setMaxResults(1000)
        ->getQuery();
        return $q->getResult();
    }

    public function findOrder($spooler,$chain,$order) { 
        $q = $this->createQueryBuilder('e')
        ->select('e.spoolerId,e.id,e.jobChain,e.title,e.priority,e.state,e.stateText,e.createdTime,e.modTime,e.ordering,e.payload,e.runTime,e.initialState,e.orderXml,e.distributedNextTime,e.occupyingClusterMemberId')
        ->orderBy('e.modTime','desc')
        ->where("e.spoolerId = :spooler")
        ->andWhere("e.jobChain = :chain")
        ->andWhere("e.id = :order")
        ->setParameter("spooler", $spooler)
        ->setParameter("chain", $chain)
        ->setParameter("order", $order)
        ->setMaxResults(1000)
        ->getQuery();
        return $q->getResult();
    }
    
    // Pour la synchronisation des historique
    public function findStates() { 
        $q = $this->createQueryBuilder('e')
        ->select('e')
        ->setMaxResults(1000)
        ->getQuery();
        return $q->getResult();
    }
}
